using EconomicCalculator.Objects.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EconomicCalculator.Objects.Territory
{
    /// <summary>
    /// Territory Read Only Interface
    /// </summary>
    public interface ITerritory
    {
        /// <summary>
        /// The name of the territory, may be ignored or autogenerated.
        /// </summary>
        string Name { get; }

        /// <summary>
        /// If the Territory is adjacent to a sea or body of water.
        /// </summary>
        bool Coastal { get; }

        /// <summary>
        /// Whether the territory has a static lake or sea contained within it.
        /// </summary>
        bool Lake { get; }

        /// <summary>
        /// The total size of the Territory in acres, including sea.
        /// </summary>
        long Size { get; }

        /// <summary>
        /// The land available in acres.
        /// </summary>
        long Land { get; }

        /// <summary>
        /// The Water in the territory measured in acres.
        /// </summary>
        long Water { get; }

        /// <summary>
        /// The number of each plots available. 
        /// (each is equal to 1/8 an acre) index.
        /// The index in <see cref="RequiredItems.LandOptions"/> is the same as here.
        /// </summary>
        IReadOnlyList<long> Plots { get; }

        /// <summary>
        /// Neighboring Territories that are not casually connected
        /// (such as a large planet map).
        /// </summary>
        IReadOnlyList<(ITerritory neighbor, decimal distance)> Neighbors { get; }

        /// <summary>
        /// The nodes within the territory which can be mined.
        /// </summary>
        IReadOnlyList<(IProduct resource, decimal stockpile, int depth)> Nodes { get; }

        /// <summary>
        /// The resources available at the surface of the territory.
        /// </summary>
        IReadOnlyList<(IProduct resource, decimal amount)> Resources { get; }
    }
}
